---
blank_issues_enabled: false
contact_links:
  - name: 💬 Questions & Help
    url: https://github.com/California-Community-College-Tech-Group/.github/blob/develop/QUESTIONS.md
    about: If you have questions, visit GitHub Discussions and Wiki pages
